#!/usr/bin/env php
<?php
require __DIR__.'/vendor/autoload.php';
require __DIR__.'/src/Core/bootstrap.php';

use Symfony\Component\Console\Application;
use App\Commands\{Fresh, NewSite, RebuildIndex};


$application = new Application();

$application->add(new Fresh());
$application->add(new NewSite());
$application->add(new RebuildIndex());
$application->run();
