#!/usr/bin/env php
<?php
require __DIR__.'/vendor/autoload.php';
require __DIR__.'/src/Core/bootstrap.php';

use Symfony\Component\Console\Application;
use App\Commands\{Fresh, NewSite, RebuildIndex};


$application = new Application();

/**
 * Not all these commands exist yet
 *
 * php vm fresh
 * php vm new
 * php vm new:yaml
 * php vm new:db
 * php vm rebuild
 * php vm remove
 * php vm remove:db
 * php vm update:yaml
 */

$application->add(new Fresh());
$application->add(new NewSite());
$application->add(new RebuildIndex());
$application->run();
